let AUTH0_DOMAIN = process.env.REACT_APP_AUTH0_DOMAIN;
let AUTH0_CLIENT_ID = process.env.REACT_APP_AUTH0_CLIENT_ID;
let AUTH0_AUDIENCE = process.env.REACT_APP_AUTH0_AUDIENCE;
let AUTH0_CALLBACK = process.env.REACT_APP_AUTH0_CALLBACK_URL;

if (process.env.NODE_ENV !== 'development') {
  AUTH0_DOMAIN = window.AUTH0_DOMAIN;
  AUTH0_CLIENT_ID = window.AUTH0_CLIENT_ID;
  AUTH0_AUDIENCE = window.AUTH0_AUDIENCE;
  AUTH0_CALLBACK = window.AUTH0_CALLBACK;
}

export { AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_AUDIENCE, AUTH0_CALLBACK };
